# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x06retail\"\x15\n\x05Order\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3')



_ORDER = DESCRIPTOR.message_types_by_name['Order']
Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:retail.Order)
  })
_sym_db.RegisterMessage(Order)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDER._serialized_start=25
  _ORDER._serialized_end=46
# @@protoc_insertion_point(module_scope)
